# ▶ Fontes específicas deste tema
font_family      Dank Mono Nerd Font
bold_font        Cascadia Code Regular
italic_font      Cascadia Code Light Italic
bold_italic_font Cascadia Code Regular Italic

# Cursor
cursor #ff79c6
cursor_shape beam
cursor_blink_interval 0.6
cursor_stop_blinking_after 0
cursor_underline_thickness 2.0
cursor_trail 10
cursor_trail_start_threshold 0

# Seleção
selection_foreground #000000
selection_background #ff79c6

# Cores (Dracula inspirado)
foreground #f8f8f2
background #000000
background_opacity 1
background_blur 90

# Tab Bar
tab_bar_style powerline
active_tab_background #282a36
active_tab_foreground #ff79c6
inactive_tab_background #1a1a1a
inactive_tab_foreground #6272a4
tab_separator ""

# Borda
active_border_color #ff79c6
inactive_border_color #44475a
bell_border_color #ff5555
draw_minimal_borders yes

# Paleta
color0   #21222c
color8   #6272a4
color1   #ff5555
color9   #ff6e6e
color2   #50fa7b
color10  #69ff94
color3   #f1fa8c
color11  #ffffa5
color4   #bd93f9
color12  #d6acff
color5   #ff79c6
color13  #ff92df
color6   #8be9fd
color14  #a4ffff
color7   #f8f8f2
color15  #ffffff

# Extras
color16  #ffb86c
color17  #ff5555
color18  #44475a
color19  #282a36
color20  #f1fa8c
color21  #6272a4
color22  #8be9fd
color23  #50fa7b
